from collections import defaultdict 



class Country:
    def __init__(self, data):
        self.name = data["name"]["common"]
        self.official_name = data["name"]["official"]
        # self.native_names = data.get("nativeName", {})
        # self.tld = data.get("tld", [])
        # self.cca2 = data.get("cca2", "")
        # self.currencies = data.get("currencies", {})
        self.capital = data.get("capital", [])
        self.region = data.get("region", "")
        self.subregion = data.get("subregion", "")
        self.languages = data.get("languages", {})
        # self.translations = data.get("translations", {})
        self.latlng = data.get("latlng", [])
        self.area = data.get("area", 0)
        self.population = data.get("population", 0)
        # self.flags = data.get("flags", {})
        self.maps = data.get("maps", {})

# Organize counties into tree structure. branches are splited by region, subregion and country name.
# country position index of the list is stored instead of the
def organizeCountiesByLoc(countries):
    regions = dict()
    for idx, country in enumerate(countries):
        if country.region in regions:
            if country.subregion in regions[country.region]:
                regions[country.region][country.subregion][country.name] = countries
            else:
                regions[country.region][country.subregion] = {country.name: countries}
        else:
            regions[country.region] = {country.subregion: {country.name: countries}}
    return regions


def distance(latlng1, latlng2):
    return ((latlng1[0] - latlng2[0])**2 + (latlng1[1] - latlng2[1])**2)**0.5

def getNearByCountries(countries):
    nearby_countries = defaultdict(list)
    distance_threshold = 10
    for country in countries:
        for country2 in countries:
            if country.name != country2.name:
                if distance(country.latlng, country2.latlng) < distance_threshold:
                    nearby_countries[country.name].append(country2.name)
    return nearby_countries

'''
nearby_countries = {
    "Burkina Faso": ['Mali', 'Niger', 'Benin', 'Togo', 'Ghana', 'Ivory Coast'],
    "Hong Kong": ['China', 'Macau'],
    "United Arab Emirates": ['Saudi Arabia', 'Oman', 'Qatar'],
    "Antigua and Barbuda": ['Saint Kitts and Nevis', 'Dominica'],
    "Comoros": ['Madagascar', 'Mozambique'],
    "Pitcairn Islands": ['French Polynesia', 'Easter Island'],
    "Bulgaria": ['Romania', 'Serbia', 'North Macedonia', 'Greece', 'Turkey'],
    "Djibouti": ['Eritrea', 'Ethiopia', 'Somalia'],
    "Laos": ['China', 'Vietnam', 'Cambodia', 'Thailand', 'Myanmar'],
    "Lebanon": ['Syria', 'Israel'],
    "Panama": ['Costa Rica', 'Colombia'],
    "Ecuador": ['Colombia', 'Peru'],
    "Barbados": ['Saint Vincent and the Grenadines', 'Saint Lucia'],
    "Isle of Man": ['United Kingdom', 'Ireland'],
    "Bhutan": ['India', 'China'],
    "Burundi": ['Rwanda', 'Tanzania', 'Democratic Republic of the Congo'],
    "China": ['Mongolia', 'Russia', 'North Korea', 'South Korea', 'Vietnam', 'Laos', 'Myanmar', 'India', 'Bhutan', 'Nepal', 'Pakistan', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan', 'Kazakhstan', 'Hong Kong', 'Macau', 'Taiwan'],
    "Norfolk Island": ['New Zealand', 'Australia'],
    "Libya": ['Egypt', 'Sudan', 'Chad', 'Niger', 'Algeria', 'Tunisia'],
    "Bosnia and Herzegovina": ['Croatia', 'Serbia', 'Montenegro'],
    "Tuvalu": ['Fiji', 'Samoa'],
    "Angola": ['Congo', 'Democratic Republic of the Congo', 'Zambia', 'Namibia'],
    "Madagascar": ['Mozambique', 'Comoros'],
    "Mauritania": ['Western Sahara', 'Algeria', 'Mali', 'Senegal'],
    "Anguilla": ['Saint Martin', 'Saint Barthélemy'],
    "Jersey": ['France', 'United Kingdom'],
    "Cape Verde": ['Senegal', 'Mauritania'],
    "United States Virgin Islands": ['Puerto Rico', 'British Virgin Islands'],
    "Northern Mariana Islands": ['Guam', 'Philippines'],
    "Niue": ['Tonga', 'Samoa'],
    "United States Minor Outlying Islands": ['Hawaii (USA)', 'Philippines'],
    "Mexico": ['United States', 'Guatemala', 'Belize'],
    "Sri Lanka": ['India', 'Maldives'],
    "Venezuela": ['Colombia', 'Brazil', 'Guyana'],
    "Falkland Islands": ['Argentina', 'Chile'],
    "Malawi": ['Tanzania', 'Mozambique', 'Zambia'],
    "San Marino": ['Italy'],
    "Turks and Caicos Islands": ['Bahamas', 'Cuba'],
    "Saint Pierre and Miquelon": ['Canada'],
    "Suriname": ['Guyana', 'Brazil', 'French Guiana'],
    "Guinea": ['Guinea-Bissau', 'Senegal', 'Mali', 'Ivory Coast', 'Liberia', 'Sierra Leone'],
    "Zimbabwe": ['Zambia', 'Mozambique', 'South Africa', 'Botswana'],
    "Rwanda": ['Uganda', 'Tanzania', 'Burundi', 'Democratic Republic of the Congo'],
    "Kyrgyzstan": ['Kazakhstan', 'Uzbekistan', 'Tajikistan', 'China'],
    "Russia": ['Norway', 'Finland', 'Estonia', 'Latvia', 'Lithuania', 'Poland', 'Belarus', 'Ukraine', 'Georgia', 'Azerbaijan', 'Kazakhstan', 'China', 'Mongolia', 'North Korea'],
    "Uzbekistan": ['Kazakhstan', 'Turkmenistan', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan'],
    "Belgium": ['Netherlands', 'Germany', 'Luxembourg', 'France'],
    "Åland Islands": ['Sweden', 'Finland'],
    "Western Sahara": ['Morocco', 'Mauritania'],
    "Mayotte": ['Comoros', 'Madagascar'],
    "Morocco": ['Western Sahara', 'Algeria', 'Spain (Ceuta and Melilla)'],
    "Martinique": ['Saint Lucia', 'Dominica'],
    "France": ['Belgium', 'Luxembourg', 'Germany', 'Switzerland', 'Italy', 'Monaco', 'Spain', 'Andorra'],
    "Tanzania": ['Kenya', 'Uganda', 'Rwanda', 'Burundi', 'Democratic Republic of the Congo', 'Zambia', 'Malawi', 'Mozambique'],
    "Cayman Islands": ['Cuba', 'Jamaica'],
    "Iran": ['Iraq', 'Turkey', 'Armenia', 'Azerbaijan', 'Turkmenistan', 'Afghanistan', 'Pakistan'],
    "Israel": ['Lebanon', 'Syria', 'Jordan', 'Egypt', 'Palestine'],
    "Cameroon": ['Nigeria', 'Chad', 'Central African Republic', 'Republic of the Congo', 'Gabon', 'Equatorial Guinea'],
    "Singapore": ['Malaysia', 'Indonesia'],
    "Croatia": ['Slovenia', 'Hungary', 'Serbia', 'Bosnia and Herzegovina', 'Montenegro'],
    "Myanmar": ['China', 'Laos', 'Thailand', 'Bangladesh', 'India'],
    "Grenada": ['Saint Vincent and the Grenadines', 'Trinidad and Tobago'],
    "Canada": ['United States'],
    "Argentina": ['Chile', 'Bolivia', 'Paraguay', 'Brazil', 'Uruguay'],
    "Réunion": ['Mauritius', 'Madagascar'],
    "Malaysia": ['Thailand', 'Indonesia', 'Brunei', 'Singapore'],
    "Eswatini": ['Mozambique', 'South Africa'],
    "Faroe Islands": ['Iceland', 'Norway'],
    "Sierra Leone": ['Guinea', 'Liberia'],
    "Uganda": ['Kenya', 'South Sudan', 'Democratic Republic of the Congo', 'Rwanda', 'Tanzania'],
    "American Samoa": ['Samoa', 'Tonga'],
    "Ivory Coast": ['Liberia', 'Guinea', 'Mali', 'Burkina Faso', 'Ghana'],
    "Equatorial Guinea": ['Gabon', 'Cameroon'],
    "Pakistan": ['India', 'China', 'Afghanistan', 'Iran'],
    "Monaco": ['France', 'Italy'],
    "Cook Islands": ['French Polynesia', 'American Samoa'],
    "Bolivia": ['Peru', 'Brazil', 'Paraguay', 'Argentina', 'Chile'],
    "Cyprus": ['Greece', 'Turkey'],
    "Fiji": ['Vanuatu', 'Tonga', 'Samoa'],
    "Brazil": ['French Guiana', 'Suriname', 'Guyana', 'Venezuela', 'Colombia', 'Peru', 'Bolivia', 'Paraguay', 'Argentina', 'Uruguay'],
    "Ukraine": ['Poland', 'Slovakia', 'Hungary', 'Romania', 'Moldova', 'Belarus', 'Russia'],
    "Palau": ['Philippines', 'Indonesia'],
    "Bahrain": ['Saudi Arabia', 'Qatar'],
    "Gambia": ['Senegal'],
    "Poland": ['Germany', 'Czech Republic', 'Slovakia', 'Ukraine', 'Belarus', 'Lithuania', 'Russia (Kaliningrad Oblast)'],
    "Cuba": ['United States (Guantánamo Bay)', 'Bahamas', 'Haiti', 'Jamaica'],
    "Jordan": ['Syria', 'Iraq', 'Saudi Arabia', 'Israel', 'Palestine'],
    "Slovenia": ['Italy', 'Austria', 'Hungary', 'Croatia'],
    "French Southern and Antarctic Lands": ['Madagascar', 'Mauritius'],
    "Turkmenistan": ['Kazakhstan', 'Uzbekistan', 'Afghanistan', 'Iran'],
    "Luxembourg": ['Belgium', 'Germany', 'France'],
    "Ghana": ['Ivory Coast', 'Burkina Faso', 'Togo'],
    "Moldova": ['Ukraine', 'Romania'],
    "Eritrea": ['Sudan', 'Ethiopia', 'Djibouti'],
    "Spain": ['Portugal', 'France', 'Morocco (Ceuta and Melilla)'],
    "Ethiopia": ['Eritrea', 'Djibouti', 'Somalia', 'Kenya', 'South Sudan', 'Sudan'],
    "Mozambique": ['Tanzania', 'Malawi', 'Zambia', 'Zimbabwe', 'South Africa', 'Swaziland (Eswatini)'],
    "Sint Maarten": ['Saint Martin', 'Anguilla'],
    "Syria": ['Turkey', 'Iraq', 'Jordan', 'Israel', 'Lebanon'],
    "Bangladesh": ['India', 'Myanmar'],
    "Vietnam": ['China', 'Laos', 'Cambodia'],
    "Netherlands": ['Belgium', 'Germany'],
    "Andorra": ['France', 'Spain'],
    "Taiwan": ['China', 'Philippines', 'Japan'],
    "Christmas Island": ['Australia', 'Indonesia'],
    "Samoa": ['American Samoa', 'Tonga'],
    "Guinea-Bissau": ['Senegal', 'Guinea'],
    "Puerto Rico": ['Dominican Republic', 'Virgin Islands'],
    "Papua New Guinea": ['Indonesia', 'Solomon Islands'],
    "Guernsey": ['Jersey', 'France'],
    "Uruguay": ['Argentina', 'Brazil'],
    "Australia": ['Indonesia', 'Papua New Guinea', 'New Zealand'],
    "North Korea": ['South Korea', 'China', 'Russia'],
    "Bouvet Island": ['South Georgia and the South Sandwich Islands'],
    "Estonia": ['Latvia', 'Russia', 'Finland'],
    "Haiti": ['Dominican Republic'],
    "Algeria": ['Tunisia', 'Libya', 'Niger', 'Mali', 'Mauritania', 'Western Sahara', 'Morocco'],
    "Togo": ['Ghana', 'Benin', 'Burkina Faso'],
    "French Guiana": ['Brazil', 'Suriname'],
    "Dominica": ['Martinique', 'Guadeloupe'],
    "São Tomé and Príncipe": ['Gabon', 'Equatorial Guinea'],
    "Egypt": ['Libya', 'Sudan', 'Israel', 'Palestine (Gaza Strip)'],
    "Guatemala": ['Mexico', 'Belize', 'Honduras', 'El Salvador'],
    "Norway": ['Sweden', 'Finland', 'Russia'],
    "Greece": ['Albania', 'North Macedonia', 'Bulgaria', 'Turkey'],
    "Belarus": ['Latvia', 'Lithuania', 'Poland', 'Ukraine', 'Russia'],
    "Denmark": ['Germany', 'Sweden'],
    "Heard Island and McDonald Islands": ['Australia', 'Antarctica'],
    "Indonesia": ['Papua New Guinea', 'East Timor', 'Australia', 'Singapore', 'Malaysia', 'Philippines'],
    "Chile": ['Peru', 'Bolivia', 'Argentina'],
    "Palestine": ['Israel', 'Jordan', 'Egypt'],
    "United Kingdom": ['Ireland', 'France'],
    "Saint Kitts and Nevis": ['Antigua and Barbuda', 'Montserrat'],
    "Saint Barthélemy": ['Saint Martin', 'Anguilla'],
    "Nicaragua": ['Honduras', 'Costa Rica'],
    "Tunisia": ['Libya', 'Algeria'],
    "Guam": ['Northern Mariana Islands', 'Philippines'],
    "Macau": ['China', 'Hong Kong'],
    "French Polynesia": ['Cook Islands', 'Pitcairn Islands'],
    "Finland": ['Sweden', 'Norway', 'Russia'],
    "Seychelles": ['Mauritius', 'Madagascar'],
    "South Georgia": ['Falkland Islands', 'Antarctica'],
    "Jamaica": ['Cayman Islands', 'Cuba'],
    "Slovakia": ['Czech Republic', 'Poland', 'Ukraine', 'Hungary', 'Austria'],
    "Guyana": ['Venezuela', 'Brazil', 'Suriname'],
    "Cambodia": ['Thailand', 'Laos', 'Vietnam'],
    "Thailand": ['Myanmar', 'Laos', 'Cambodia', 'Malaysia'],
    "Micronesia": ['Palau', 'Marshall Islands'],
    "Maldives": ['Sri Lanka', 'India'],
    "Mauritius": ['Reunion', 'Madagascar'],
    "New Caledonia": ['Australia', 'Vanuatu'],
    "Philippines": ['Taiwan', 'Vietnam', 'Malaysia', 'Indonesia'],
    "Sudan": ['Egypt', 'Libya', 'Chad', 'Central African Republic', 'South Sudan', 'Ethiopia', 'Eritrea'],
    "United States": ['Canada', 'Mexico'],
    "Japan": ['Russia', 'South Korea', 'North Korea', 'China'],
    "Georgia": ['Russia', 'Armenia', 'Turkey', 'Azerbaijan'],
    "Tajikistan": ['Afghanistan', 'Uzbekistan', 'Kyrgyzstan', 'China'],
    "Antarctica": ['Argentina', 'Chile', 'New Zealand', 'Australia', 'South Africa'],
    "Republic of the Congo": ['Gabon', 'Cameroon', 'Central African Republic', 'Democratic Republic of the Congo', 'Angola'],
    "Serbia": ['Hungary', 'Romania', 'Bulgaria', 'North Macedonia', 'Albania', 'Montenegro', 'Bosnia and Herzegovina', 'Croatia'],
    "Armenia": ['Turkey', 'Georgia', 'Azerbaijan', 'Iran'],
    "Botswana": ['Namibia', 'South Africa', 'Zimbabwe', 'Zambia'],
    "Afghanistan": ['Iran', 'Turkmenistan', 'Uzbekistan', 'Tajikistan', 'China', 'Pakistan'],
    "Qatar": ['Saudi Arabia', 'United Arab Emirates', 'Bahrain'],
    "Trinidad and Tobago": ['Grenada', 'Venezuela'],
    "Yemen": ['Saudi Arabia', 'Oman'],
    "Brunei": ['Malaysia', 'Indonesia'],
    "Iceland": ['Greenland (Denmark)', 'Norway'],
    "Caribbean Netherlands": ['Aruba', 'Curaçao'],
    "Marshall Islands": ['Micronesia', 'Kiribati'],
    "Iraq": ['Turkey', 'Syria', 'Jordan', 'Saudi Arabia', 'Kuwait', 'Iran'],
    "Curaçao": ['Aruba', 'Venezuela'],
    "Kosovo": ['Serbia', 'North Macedonia', 'Albania', 'Montenegro'],
    "Albania": ['Montenegro', 'Kosovo', 'North Macedonia', 'Greece'],
    "Saint Vincent and the Grenadines": ['Saint Lucia', 'Barbados', 'Grenada'],
    "Honduras": ['Guatemala', 'El Salvador', 'Nicaragua'],
    "Tokelau": ['Samoa', 'American Samoa'],
    "Namibia": ['Angola', 'Botswana', 'South Africa', 'Zambia'],
    "Wallis and Futuna": ['Fiji', 'Samoa'],
    "Lithuania": ['Latvia', 'Belarus', 'Poland', 'Russia (Kaliningrad Oblast)'],
    "Niger": ['Algeria', 'Libya', 'Chad', 'Nigeria', 'Benin', 'Burkina Faso', 'Mali'],
    "Benin": ['Togo', 'Nigeria', 'Niger', 'Burkina Faso'],
    "India": ['Pakistan', 'China', 'Nepal', 'Bhutan', 'Myanmar', 'Bangladesh'],
    "Mali": ['Algeria', 'Niger', 'Burkina Faso', 'Ivory Coast', 'Guinea', 'Senegal', 'Mauritania'],
    "Nigeria": ['Benin', 'Niger', 'Chad', 'Cameroon'],
    "Aruba": ['Curaçao', 'Venezuela'],
    "Saudi Arabia": ['Jordan', 'Iraq', 'Kuwait', 'Bahrain', 'Qatar', 'United Arab Emirates', 'Oman', 'Yemen'],
    "Bermuda": ['United States (East Coast)'],
    "Montserrat": ['Antigua and Barbuda', 'Saint Kitts and Nevis'],
    "Kazakhstan": ['Russia', 'China', 'Kyrgyzstan', 'Uzbekistan', 'Turkmenistan'],
    "Lesotho": ['South Africa'],
    "Kiribati": ['Marshall Islands', 'Micronesia'],
    "Dominican Republic": ['Haiti', 'Puerto Rico'],
    "Ireland": ['United Kingdom'],
    "Azerbaijan": ['Russia', 'Georgia', 'Armenia', 'Iran'],
    "South Korea": ['North Korea', 'Japan'],
    "Tonga": ['Samoa', 'Fiji'],
    "Kuwait": ['Iraq', 'Saudi Arabia'],
    "Oman": ['Yemen', 'Saudi Arabia', 'United Arab Emirates'],
    "Chad": ['Libya', 'Sudan', 'Central African Republic', 'Cameroon', 'Nigeria', 'Niger'],
    "Mongolia": ['Russia', 'China'],
    "North Macedonia": ['Kosovo', 'Serbia', 'Bulgaria', 'Greece', 'Albania'],
    "DR Congo": ['Central African Republic', 'South Sudan', 'Uganda', 'Rwanda', 'Burundi', 'Tanzania', 'Zambia', 'Angola', 'Republic of the Congo'],
    "Germany": ['Denmark', 'Poland', 'Czech Republic', 'Austria', 'Switzerland', 'France', 'Luxembourg', 'Belgium', 'Netherlands'],
    "Hungary": ['Austria', 'Slovakia', 'Ukraine', 'Romania', 'Serbia', 'Croatia', 'Slovenia'],
    "Kenya": ['Ethiopia', 'Somalia', 'South Sudan', 'Uganda', 'Tanzania'],
    "Zambia": ['Tanzania', 'Malawi', 'Mozambique', 'Zimbabwe', 'Botswana', 'Namibia', 'Angola', 'Democratic Republic of the Congo'],
    "South Africa": ['Namibia', 'Botswana', 'Zimbabwe', 'Mozambique', 'Swaziland', 'Lesotho'],
    "Latvia": ['Estonia', 'Lithuania', 'Belarus', 'Russia'],
    "Timor-Leste": ['Indonesia'],
    "Peru": ['Ecuador', 'Colombia', 'Brazil', 'Bolivia', 'Chile'],
    "Switzerland": ['France', 'Germany', 'Austria', 'Liechtenstein', 'Italy'],
    "Bahamas": ['Cuba', 'United States (Florida)'],
    "Gabon": ['Equatorial Guinea', 'Cameroon', 'Republic of the Congo', 'Democratic Republic of the Congo'],
    "Liberia": ['Sierra Leone', 'Guinea', 'Ivory Coast'],
    "South Sudan": ['Sudan', 'Ethiopia', 'Kenya', 'Democratic Republic of the Congo', 'Central African Republic', 'Uganda'],
    "Gibraltar": ['Spain'],
    "Saint Lucia": ['Martinique', 'Saint Vincent and the Grenadines'],
    "Portugal": ['Spain'],
    "Greenland": ['Iceland', 'Canada'],
    "Guadeloupe": ['Dominica', 'Montserrat'],
    "Saint Martin": ['Sint Maarten', 'Anguilla', 'Saint Barthélemy'],
    "Costa Rica": ['Nicaragua', 'Panama'],
    "Czechia": ['Germany', 'Poland', 'Slovakia', 'Austria'],
    "Montenegro": ['Bosnia and Herzegovina', 'Serbia', 'Kosovo', 'Albania', 'Croatia'],
    "Cocos (Keeling) Islands": ['Christmas Island', 'Indonesia'],
    "Sweden": ['Norway', 'Finland', 'Denmark'],
    "British Indian Ocean Territory": ['Maldives', 'Seychelles'],
    "Somalia": ['Ethiopia', 'Djibouti', 'Kenya'],
    "Malta": ['Italy', 'Tunisia'],
    "Saint Helena, Ascension and Tristan da Cunha": ['South Africa'],
    "Colombia": ['Panama', 'Venezuela', 'Brazil', 'Peru', 'Ecuador'],
    "Turkey": ['Greece', 'Bulgaria', 'Georgia', 'Armenia', 'Iran', 'Iraq', 'Syria'],
    "Belize": ['Mexico', 'Guatemala'],
    "Solomon Islands": ['Papua New Guinea', 'Vanuatu'],
    "British Virgin Islands": ['United States Virgin Islands', 'Puerto Rico'],
    "Vatican City": ['Italy'],
    "Senegal": ['Gambia', 'Guinea-Bissau', 'Guinea', 'Mali', 'Mauritania'],
    "Central African Republic": ['Chad', 'Sudan', 'South Sudan', 'Democratic Republic of the Congo', 'Republic of the Congo', 'Cameroon'],
    "Liechtenstein": ['Switzerland', 'Austria'],
    "Nauru": ['Kiribati', 'Marshall Islands'],
    "Romania": ['Ukraine', 'Moldova', 'Bulgaria', 'Serbia', 'Hungary'],
    "Austria": ['Germany', 'Czech Republic', 'Slovakia', 'Hungary', 'Slovenia', 'Italy', 'Switzerland', 'Liechtenstein'],
    "Nepal": ['China', 'India'],
    "Paraguay": ['Bolivia', 'Brazil', 'Argentina'],
    "New Zealand": ['Australia', 'Fiji', 'New Caledonia'],
    "Italy": ['France', 'Switzerland', 'Austria', 'Slovenia', 'San Marino', 'Vatican City'],
    "El Salvador": ['Guatemala', 'Honduras'],
    "Svalbard and Jan Mayen": ['Norway', 'Greenland'],
    "Vanuatu": ['New Caledonia', 'Fiji', 'Solomon Islands'],
    "Antarctic": ['Australia', 'New Zealand', 'South Africa', 'Argentina', 'Chile'],
}

'''

